version: '3.8'

services:
  storybook:
    build:
      context: ../..
      dockerfile: apps/storybook/Dockerfile
      target: development
    ports:
      - "6006:6006"
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/apps/storybook/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /app/apps/storybook

